/*
 * swaggerpetstore_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
package models_pkg

import(
    "encoding/json"
)

/**
 * Type definition for Status6Enum enum
 */
type Status6Enum int

/**
 * Value collection for Status6Enum enum
 */
const (
    Status6_AVAILABLE Status6Enum = 1 + iota
    Status6_PENDING
    Status6_SOLD
)

func (r Status6Enum) MarshalJSON() ([]byte, error) { 
    s := Status6EnumToValue(r)
    return json.Marshal(s) 
} 

func (r *Status6Enum) UnmarshalJSON(data []byte) error { 
    var s string 
    json.Unmarshal(data, &s)
    v :=  Status6EnumFromValue(s)
    *r = v 
    return nil 
 } 


/**
 * Converts Status6Enum to its string representation
 */
func Status6EnumToValue(status6Enum Status6Enum) string {
    switch status6Enum {
        case Status6_AVAILABLE:
    		return "available"		
        case Status6_PENDING:
    		return "pending"		
        case Status6_SOLD:
    		return "sold"		
        default:
        	return "available"
    }
}

/**
 * Converts Status6Enum Array to its string Array representation
*/
func Status6EnumArrayToValue(status6Enum []Status6Enum) []string {
    convArray := make([]string,len( status6Enum))
    for i:=0; i<len(status6Enum);i++ {
        convArray[i] = Status6EnumToValue(status6Enum[i])
    }
    return convArray
}


/**
 * Converts given value to its enum representation
 */
func Status6EnumFromValue(value string) Status6Enum {
    switch value {
        case "available":
            return Status6_AVAILABLE
        case "pending":
            return Status6_PENDING
        case "sold":
            return Status6_SOLD
        default:
            return Status6_AVAILABLE
    }
}
